# Generated by Django 4.0.5 on 2023-04-18 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100, verbose_name=100)),
                ('CCTLD', models.CharField(max_length=100, verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_emp', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100, verbose_name=40)),
                ('emp_last_name', models.CharField(max_length=100, verbose_name=50)),
                ('user_name', models.CharField(max_length=100, verbose_name=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, verbose_name=50)),
                ('description', models.CharField(max_length=100, verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100, verbose_name=50)),
            ],
        ),
        migrations.CreateModel(
            name='Org_team',
            fields=[
                ('id_org_team', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, verbose_name=50)),
                ('description', models.CharField(max_length=100, verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='Org_team_mngr',
            fields=[
                ('id_team_mngr', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('id_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('id_org_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.org_team')),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory_name', models.CharField(max_length=100, verbose_name=30)),
                ('team_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.org_team_mngr')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, verbose_name=30)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name=50)),
                ('domain', models.CharField(max_length=100, verbose_name=50)),
                ('address', models.CharField(max_length=100, verbose_name=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.industry')),
            ],
        ),
    ]
