# Generated by Django 4.0.5 on 2023-04-18 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name=50)),
                ('category_code', models.CharField(max_length=100, verbose_name=50)),
                ('description', models.CharField(max_length=100, verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id_flag', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('flag_name', models.CharField(max_length=100, verbose_name=50)),
                ('description', models.CharField(max_length=100, verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id_priority', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('priority_name', models.CharField(max_length=100, verbose_name=50)),
                ('priority_code', models.CharField(max_length=100, verbose_name=50)),
                ('description', models.CharField(max_length=100, verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id_risk', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('risk_name', models.CharField(max_length=100, verbose_name=50)),
                ('risk_code', models.CharField(max_length=100, verbose_name=50)),
                ('description', models.CharField(max_length=100, verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id_source', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=100, verbose_name=50)),
                ('description', models.CharField(max_length=100, verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100, verbose_name=50)),
                ('description', models.CharField(max_length=100, verbose_name=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.employee_role'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_Product', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, verbose_name=50)),
                ('product_code', models.CharField(max_length=100, verbose_name=50)),
                ('description', models.CharField(max_length=100, verbose_name=100)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Org_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('id_org_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.org_team')),
            ],
        ),
    ]
