# Generated by Django 4.0.5 on 2023-04-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_flag_priority_risk_source_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(max_length=100, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='country',
            name='CCTLD',
            field=models.CharField(max_length=100, verbose_name='CCTLD'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
