# Generated by Django 4.0.5 on 2023-04-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_alter_industry_industry_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.CharField(max_length=100, verbose_name='Descriptions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
            ],
        ),
    ]
