# Generated by Django 4.0.5 on 2023-04-18 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_category_flag_priority_risk_source_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100, verbose_name=50)),
                ('website', models.CharField(max_length=100, verbose_name=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.industry')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.region')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.territory')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id_competitor', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('competitor_name', models.CharField(max_length=100, verbose_name=50)),
                ('competitor_code', models.CharField(max_length=100, verbose_name=50)),
                ('description', models.CharField(max_length=100, verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, verbose_name=50)),
                ('description', models.CharField(max_length=100, verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=300)),
                ('next_step', models.TextField(max_length=300)),
                ('due_date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.source')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=40)),
                ('last_name', models.CharField(max_length=100, verbose_name=50)),
                ('email', models.CharField(max_length=100, verbose_name=50)),
                ('number', models.CharField(max_length=100, verbose_name=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.account')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contact_role')),
            ],
        ),
    ]
