# Generated by Django 4.0.5 on 2023-04-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='persona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.CharField(max_length=100, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='competitor_code',
            field=models.CharField(max_length=100, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='competitor_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='contact_role',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contact_role',
            name='role_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='detail',
            field=models.TextField(max_length=300, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='next_step',
            field=models.TextField(max_length=300, verbose_name='Next Step'),
        ),
    ]
